version: "3.9"

volumes:
  database_data:

services:
  database:
    image: postgres:13
    ports:
      - target: 5432
        published: 5000
    volumes:
      - type: volume
        source: database_data
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_DB: boilerplate
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  initialize_database:
    build: ./database
    depends_on:
      - database
    volumes:
      - type: bind
        source: ./database/migrations
        target: /usr/local/etc/sqlx/migrations
        read_only: true
    environment:
      BOILERPLATE_MIGRATE_DATABASE_URL: postgres://postgres@database:5432/boilerplate?password=password
      BOILERPLATE_MIGRATE_WEBSERVER_USER_PASSWORD: password
    command:
      - migrate
      - run

  webapi:
    build: ./webapi
    ports:
      - target: 80
        published: 4000
    depends_on:
      - database
    env_file:
      - .env
    environment:
      BOILERPLATE_API_PORT: 80
      BOILERPLATE_DATABASE_URL: postgres://webserver@database:5432/boilerplate?password=password
